# Generated by Django 5.1.1 on 2024-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_type",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
