# Generated by Django 5.1.1 on 2024-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_movie_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default="images/none/noimage.jpg", upload_to="images/"
            ),
        ),
    ]
